Настроил nginx

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,226 +1,274 @@
 version: "3.8"
 
-volumes:
-  certs:
-    driver: local
-  esdata01:
-    driver: local
-  kibanadata:
-    driver: local
-  metricbeatdata01:
-    driver: local
-  filebeatdata01:
-    driver: local
-  logstashdata01:
-    driver: local
+# volumes:
+#   certs:
+#     driver: local
+#   esdata01:
+#     driver: local
+#   kibanadata:
+#     driver: local
+#   metricbeatdata01:
+#     driver: local
+#   filebeatdata01:
+#     driver: local
+#   logstashdata01:
+#     driver: local
 
 networks:
-  default:
-    name: elastic
-    external: false
+  # default:
+  #   name: movies_network
+  movies_network:
+    # external: false
 
 services:
-  setup:
-    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
-    volumes:
-      - certs:/usr/share/elasticsearch/config/certs
-    user: "0"
-    command: >
-      bash -c '
-        if [ x${ELASTIC_PASSWORD} == x ]; then
-          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
-          exit 1;
-        elif [ x${KIBANA_PASSWORD} == x ]; then
-          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
-          exit 1;
-        fi;
-        if [ ! -f config/certs/ca.zip ]; then
-          echo "Creating CA";
-          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
-          unzip config/certs/ca.zip -d config/certs;
-        fi;
-        if [ ! -f config/certs/certs.zip ]; then
-          echo "Creating certs";
-          echo -ne \
-          "instances:\n"\
-          "  - name: es01\n"\
-          "    dns:\n"\
-          "      - es01\n"\
-          "      - localhost\n"\
-          "    ip:\n"\
-          "      - 127.0.0.1\n"\
-          "  - name: kibana\n"\
-          "    dns:\n"\
-          "      - kibana\n"\
-          "      - localhost\n"\
-          "    ip:\n"\
-          "      - 127.0.0.1\n"\
-          > config/certs/instances.yml;
-          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
-          unzip config/certs/certs.zip -d config/certs;
-        fi;
-        echo "Setting file permissions"
-        chown -R root:root config/certs;
-        find . -type d -exec chmod 750 \{\} \;;
-        find . -type f -exec chmod 640 \{\} \;;
-        echo "Waiting for Elasticsearch availability";
-        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
-        echo "Setting kibana_system password";
-        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
-        echo "All done!";
-      '
-    healthcheck:
-      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
-      interval: 1s
-      timeout: 5s
-      retries: 120
+#   setup:
+#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+#     volumes:
+#       - certs:/usr/share/elasticsearch/config/certs
+#     user: "0"
+#     command: >
+#       bash -c '
+#         if [ x${ELASTIC_PASSWORD} == x ]; then
+#           echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
+#           exit 1;
+#         elif [ x${KIBANA_PASSWORD} == x ]; then
+#           echo "Set the KIBANA_PASSWORD environment variable in the .env file";
+#           exit 1;
+#         fi;
+#         if [ ! -f config/certs/ca.zip ]; then
+#           echo "Creating CA";
+#           bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
+#           unzip config/certs/ca.zip -d config/certs;
+#         fi;
+#         if [ ! -f config/certs/certs.zip ]; then
+#           echo "Creating certs";
+#           echo -ne \
+#           "instances:\n"\
+#           "  - name: es01\n"\
+#           "    dns:\n"\
+#           "      - es01\n"\
+#           "      - localhost\n"\
+#           "    ip:\n"\
+#           "      - 127.0.0.1\n"\
+#           "  - name: kibana\n"\
+#           "    dns:\n"\
+#           "      - kibana\n"\
+#           "      - localhost\n"\
+#           "    ip:\n"\
+#           "      - 127.0.0.1\n"\
+#           > config/certs/instances.yml;
+#           bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
+#           unzip config/certs/certs.zip -d config/certs;
+#         fi;
+#         echo "Setting file permissions"
+#         chown -R root:root config/certs;
+#         find . -type d -exec chmod 750 \{\} \;;
+#         find . -type f -exec chmod 640 \{\} \;;
+#         echo "Waiting for Elasticsearch availability";
+#         until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
+#         echo "Setting kibana_system password";
+#         until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
+#         echo "All done!";
+#       '
+#     healthcheck:
+#       test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
+#       interval: 1s
+#       timeout: 5s
+#       retries: 120
+#     networks:
+#       - movies_network
 
-  es01:
-    depends_on:
-      setup:
-        condition: service_healthy
-    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
-    restart: unless-stopped
-    labels:
-      co.elastic.logs/module: elasticsearch
-    volumes:
-      - certs:/usr/share/elasticsearch/config/certs
-      - esdata01:/usr/share/elasticsearch/data
-    ports:
-      - ${ES_PORT}:9200
-    environment:
-      - node.name=es01
-      - cluster.name=${CLUSTER_NAME}
-      - discovery.type=single-node
-      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
-      - bootstrap.memory_lock=true
-      - xpack.security.enabled=true
-      - xpack.security.http.ssl.enabled=true
-      - xpack.security.http.ssl.key=certs/es01/es01.key
-      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
-      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
-      - xpack.security.transport.ssl.enabled=true
-      - xpack.security.transport.ssl.key=certs/es01/es01.key
-      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
-      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
-      - xpack.security.transport.ssl.verification_mode=certificate
-      - xpack.license.self_generated.type=${LICENSE}
-      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
-    ulimits:
-      memlock:
-        soft: -1
-        hard: -1
-    healthcheck:
-      test:
-        [
-          "CMD-SHELL",
-          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
-        ]
-      interval: 10s
-      timeout: 10s
-      retries: 120
+#   es01:
+#     depends_on:
+#       setup:
+#         condition: service_healthy
+#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+#     restart: unless-stopped
+#     labels:
+#       co.elastic.logs/module: elasticsearch
+#     volumes:
+#       - certs:/usr/share/elasticsearch/config/certs
+#       - esdata01:/usr/share/elasticsearch/data
+#     ports:
+#       - ${ES_PORT}:9200
+#     environment:
+#       - node.name=es01
+#       - cluster.name=${CLUSTER_NAME}
+#       - discovery.type=single-node
+#       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+#       - bootstrap.memory_lock=true
+#       - xpack.security.enabled=true
+#       - xpack.security.http.ssl.enabled=true
+#       - xpack.security.http.ssl.key=certs/es01/es01.key
+#       - xpack.security.http.ssl.certificate=certs/es01/es01.crt
+#       - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
+#       - xpack.security.transport.ssl.enabled=true
+#       - xpack.security.transport.ssl.key=certs/es01/es01.key
+#       - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
+#       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
+#       - xpack.security.transport.ssl.verification_mode=certificate
+#       - xpack.license.self_generated.type=${LICENSE}
+#       - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
+#     ulimits:
+#       memlock:
+#         soft: -1
+#         hard: -1
+#     healthcheck:
+#       test:
+#         [
+#           "CMD-SHELL",
+#           "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
+#         ]
+#       interval: 10s
+#       timeout: 10s
+#       retries: 120
+#     networks:
+#       - movies_network
 
-  kibana:
-    depends_on:
-      es01:
-        condition: service_healthy
-    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
-    restart: unless-stopped
-    labels:
-      co.elastic.logs/module: kibana
-    volumes:
-      - certs:/usr/share/kibana/config/certs
-      - kibanadata:/usr/share/kibana/data
-    ports:
-      - ${KIBANA_PORT}:5601
-    environment:
-      - SERVERNAME=kibana
-      - ELASTICSEARCH_HOSTS=https://es01:9200
-      - ELASTICSEARCH_USERNAME=kibana_system
-      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
-      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
-      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
-      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
-      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
-      - "KB_JAVA_OPTS=-Xms256m -Xmx256m"
-    healthcheck:
-      test:
-        [
-          "CMD-SHELL",
-          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
-        ]
-      interval: 10s
-      timeout: 10s
-      retries: 120
+#   kibana:
+#     depends_on:
+#       es01:
+#         condition: service_healthy
+#     image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
+#     restart: unless-stopped
+#     labels:
+#       co.elastic.logs/module: kibana
+#     volumes:
+#       - certs:/usr/share/kibana/config/certs
+#       - kibanadata:/usr/share/kibana/data
+#     ports:
+#       - ${KIBANA_PORT}:5601
+#     environment:
+#       - SERVERNAME=kibana
+#       - ELASTICSEARCH_HOSTS=https://es01:9200
+#       - ELASTICSEARCH_USERNAME=kibana_system
+#       - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
+#       - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
+#       - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
+#       - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
+#       - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
+#       - "KB_JAVA_OPTS=-Xms256m -Xmx256m"
+#     healthcheck:
+#       test:
+#         [
+#           "CMD-SHELL",
+#           "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
+#         ]
+#       interval: 10s
+#       timeout: 10s
+#       retries: 120
+#     networks:
+#       - movies_network
 
-  metricbeat01:
-    depends_on:
-      es01:
-        condition: service_healthy
-      kibana:
-        condition: service_healthy
-    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
-    restart: unless-stopped
-    volumes:
-      - certs:/usr/share/metricbeat/certs
-      - metricbeatdata01:/usr/share/metricbeat/data
-      - ".elk/config_elk/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
-      - "/var/run/docker.sock:/var/run/docker.sock:ro"
-      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
-      - "/proc:/hostfs/proc:ro"
-      - "/:/hostfs:ro"
-    command: sh -c "cp /usr/share/metricbeat/metricbeat.yml /tmp/metricbeat.yml && metricbeat -c /tmp/metricbeat.yml"
-    environment:
-      - ELASTIC_USER=elastic
-      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
-      - ELASTIC_HOSTS=https://es01:9200
-      - KIBANA_HOSTS=http://kibana:5601
-      - LOGSTASH_HOSTS=http://logstash01:9600
+#   metricbeat01:
+#     depends_on:
+#       es01:
+#         condition: service_healthy
+#       kibana:
+#         condition: service_healthy
+#     image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
+#     restart: unless-stopped
+#     volumes:
+#       - certs:/usr/share/metricbeat/certs
+#       - metricbeatdata01:/usr/share/metricbeat/data
+#       - "./elk/config_elk/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
+#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
+#       - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
+#       - "/proc:/hostfs/proc:ro"
+#       - "/:/hostfs:ro"
+#     command: sh -c "cp /usr/share/metricbeat/metricbeat.yml /tmp/metricbeat.yml && metricbeat -c /tmp/metricbeat.yml"
+#     environment:
+#       - ELASTIC_USER=elastic
+#       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+#       - ELASTIC_HOSTS=https://es01:9200
+#       - KIBANA_HOSTS=http://kibana:5601
+#       - LOGSTASH_HOSTS=http://logstash01:9600
+#     networks:
+#       - movies_network
 
-  filebeat01:
-    depends_on:
-      es01:
-        condition: service_healthy
-    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
-    restart: unless-stopped
-    user: root
-    volumes:
-      - certs:/usr/share/filebeat/certs
-      - filebeatdata01:/usr/share/filebeat/data
-      - "./fastapi_logs:/usr/share/filebeat/fastapi/"
-      - "./nginx_logs/:/usr/share/filebeat/nginx/"
-      - ".elk/config_elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
-      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
-      - "/var/run/docker.sock:/var/run/docker.sock:ro"
-    command: sh -c "cp /usr/share/filebeat/filebeat.yml /tmp/filebeat.yml && filebeat -c /tmp/filebeat.yml"
-    environment:
-      - ELASTIC_USER=elastic
-      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
-      - ELASTIC_HOSTS=https://es01:9200
-      - KIBANA_HOSTS=http://kibana:5601
-      - LOGSTASH_HOSTS=http://logstash01:9600
+#   filebeat01:
+#     depends_on:
+#       es01:
+#         condition: service_healthy
+#     image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
+#     restart: unless-stopped
+#     user: root
+#     volumes:
+#       - certs:/usr/share/filebeat/certs
+#       - filebeatdata01:/usr/share/filebeat/data
+#       - "./fastapi_logs:/usr/share/filebeat/fastapi/"
+#       - "./nginx_logs/:/usr/share/filebeat/nginx/"
+#       - "./elk/config_elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
+#       - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
+#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
+#     command: sh -c "cp /usr/share/filebeat/filebeat.yml /tmp/filebeat.yml && filebeat -c /tmp/filebeat.yml"
+#     environment:
+#       - ELASTIC_USER=elastic
+#       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+#       - ELASTIC_HOSTS=https://es01:9200
+#       - KIBANA_HOSTS=http://kibana:5601
+#       - LOGSTASH_HOSTS=http://logstash01:9600
+#     networks:
+#       - movies_network
 
-  logstash01:
-    depends_on:
-      es01:
-        condition: service_healthy
-      kibana:
-        condition: service_healthy
-    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
-    labels:
-      co.elastic.logs/module: logstash
-    user: root
-    ports:
-      - ${LOGSTASH_PORT}:5044/udp
-    volumes:
-      - certs:/usr/share/logstash/certs
-      - logstashdata01:/usr/share/logstash/data
-      - ".elk/config_elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
-    environment:
-      - xpack.monitoring.enabled=false
-      - ELASTIC_USER=elastic
-      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
-      - ELASTIC_HOSTS=https://es01:9200
+#   logstash01:
+#     depends_on:
+#       es01:
+#         condition: service_healthy
+#       kibana:
+#         condition: service_healthy
+#     image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
+#     labels:
+#       co.elastic.logs/module: logstash
+#     user: root
+#     ports:
+#       - ${LOGSTASH_PORT}:5044/udp
+#     volumes:
+#       - certs:/usr/share/logstash/certs
+#       - logstashdata01:/usr/share/logstash/data
+#       - "./elk/config_elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
+#     environment:
+#       - xpack.monitoring.enabled=false
+#       - ELASTIC_USER=elastic
+#       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+#       - ELASTIC_HOSTS=https://es01:9200
+#     networks:
+#       - movies_network
+
+#   mongo:
+#     image: mongo:4.4.23-rc0-focal
+#     restart: unless-stopped
+#     expose:
+#       - "27017"
+#     environment:
+#       MONGO_INITDB_DATABASE: ${MONGO_DB}
+#     volumes:
+#       - ./db/mongo:/docker-entrypoint-initdb.d
+#     healthcheck:
+#       test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
+#       interval: 30s
+#       timeout: 10s
+#       retries: 5
+#     ports:
+#       - "${MONGO_PORT}:27017"
+#     networks:
+#       - movies_network
+
+#   mongo-express:
+#     image: mongo-express:1.0.0-alpha.4
+#     restart: unless-stopped
+#     expose:
+#       - "8081"
+#     ports:
+#       - 8081:8081
+#     environment:
+#       ME_CONFIG_MONGODB_SERVER: mongo
+#       ME_CONFIG_MONGODB_PORT: 27017
+#     depends_on:
+#       mongo:
+#         condition: service_healthy
+#     networks:
+#       - movies_network
 
   nginx01:
     image: nginx:${NGINX_VERSION}
@@ -228,26 +276,33 @@ services:
     labels:
       co.elastic.logs/module: nginx
     volumes:
-      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
-      - "./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf"
+      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
+      - "./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro"
       - "./nginx_logs:/var/log/nginx"
     depends_on:
-      - fast_api
+      - ugc_2_fast_api
     ports:
-      - ${NGINX_PORT1}:80
+      - ${NGINX_PORT}:80
+    networks:
+      - movies_network
 
-  fast_api:
+  ugc_2_fast_api:
     build:
-      context: .
+      context: ./elk/.
+    hostname: ugc_2_fast_api
     restart: unless-stopped
     labels:
       co.elastic.logs/enabled: "true"
     env_file:
       - .env
+    expose:
+      - ${FAST_API_PORT}
     ports:
       - ${FAST_API_PORT}:${FAST_API_PORT}
-    depends_on:
-      - logstash01
-      - filebeat01
+    # depends_on:
+    #   - logstash01
+    #   - filebeat01
     volumes:
       - "./fastapi_logs:/var/log"
+    networks:
+      - movies_network
