Проверяю работу тестов без user_id и вывод ошибок в actions

diff --git a/.github/workflows/code-checker.yml b/.github/workflows/code-checker.yml
--- a/.github/workflows/code-checker.yml
+++ b/.github/workflows/code-checker.yml
@@ -86,6 +86,14 @@ jobs:
         run: docker-compose -f ./ugc_service/tests/functional/docker-compose.yml down
         continue-on-error: true
 
+      - name: Fail if test errors found
+        run: |
+          EXIT_CODE=$(docker wait tests)
+          if [ "$EXIT_CODE" == "1" ]; then
+            echo "Test errors found. Exiting with error."
+            exit 1
+          fi
+
       - name: Fail if errors found
         run: |
           if [ "${{ steps.run_linters.outcome }}" == "failure" ]; then
@@ -95,11 +103,6 @@ jobs:
 
           if [ "${{ steps.run_mypy.outcome }}" == "failure" ]; then
             echo "MyPy errors found. Exiting with error."
-            exit 1
-          fi
-
-          if [ "${{ steps.run_pytest.outcome }}" == "failure" ]; then
-            echo "Test errors found. Exiting with error."
             exit 1
           fi
 
